apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kahawa-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/collengine/argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: kahawa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kahawa-coders-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/collengine/argocd.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: kahawa-coder

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true