# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: devsecops-kahawa-frontend
# spec:
#   selector:
#     matchLabels:
#       app: devsecops-kahawa-frontend
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: devsecops-kahawa-frontend
#     spec:
#       containers:
#       - name: devsecops-kahawa-frontend
#         image: onekoech/devsecops-kahawa-frontend:uat-78024b5a-20230616085012
#         ports:
#         - containerPort: 3000
