apiVersion: v1
kind: Service
metadata:
  name: devsecops-kahawa-frontend-service
spec:
  selector:
    app: devsecops-kahawa-frontend
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  
